const mobiles = [
    {
        id: 1,
        title: "OPPO Reno10 5G (Silvery Grey, 256 GB) ",
        author: "Oppo",
        price: 32000,
        img: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/e/z/d/-original-imagrn6d7ggk4wjp.jpeg?q=70",
        amount: 1,
      },
      {
        id: 2,
        title: "SAMSUNG Galaxy F13 (Sunrise Copper, 64 GB)  (4 GB RAM)",
        author: "Samsung",
        price: 10999,
        img: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/x/x/s/-original-imagfhu6dcpdnqkh.jpeg?q=70",
        amount: 1,
      },
      {
        id: 3,
        title: "Infinix SMART 7 (Azure Blue, 64 GB)  (4 GB RAM)",
        author: "infinix",
        price: 7999,
        img:"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/u/c/u/-original-imagnanh2yvpc4zx.jpeg?q=70",
        amount: 1,
      },
      {
        id: 4,
        title: "POCO C55 (Forest Green, 64 GB)  (4 GB RAM)",
        author: "Poco",
        price: 7499,
        img:"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/a/6/f/-original-imagnb6nvnqz7hqq.jpeg?q=70",
        amount: 1,
      },
      {
        id: 5,
        title: "MOTOROLA g42 (Atlantic Green, 64 GB)  (4 GB RAM)",
        author: "Motorola",
        price: 9999,
        img: "https://rukminim2.flixcart.com/image/416/416/l51d30w0/mobile/n/y/v/-original-imagfsuftgdf6jxe.jpeg?q=70",
        amount: 1,
      },
      {
        id: 6,
        title: "realme 10 Pro 5G (Nebula Blue, 128 GB)  (8 GB RAM)",
        author: "Realme",
        price: 15999,
        img:"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/y/z/r/-original-imagkp8yzvqffyhc.jpeg?q=70",
        amount: 1,
      },
      {
        id: 7,
        title: "realme 10 Pro 5G (Nebula Blue, 128 GB)  (8 GB RAM)",
        author: "Realme",
        price: 13999,
        img:"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/2/t/j/narzo-n55-rmx3710-realme-original-imagzufmktk2crzq.jpeg?q=70",
        amount: 1,
      },
      {
        id: 8,
        title: "APPLE iPhone 14 (Starlight, 128 GB)",
        author: "Apple",
        price: 69999,
        img:"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/m/o/b/-original-imaghx9qkugtbfrn.jpeg?q=70",
        amount: 1,
      },
      {
        id: 9,
        title: "APPLE iPhone 13 (Starlight, 128 GB)",
        author: "Apple",
        price: 61999,
        img:"https://rukminim2.flixcart.com/image/416/416/ktketu80/mobile/s/l/c/iphone-13-mlpf3hn-a-apple-original-imag6vzz5qvejz8z.jpeg?q=70",
        amount: 1,
      },
      {
        id: 10,
        title: "APPLE iPhone 14 Pro (Space Black, 256 GB)",
        author: "Apple",
        price: 130999,
        img:"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/y/l/p/-original-imaghxemc3wtcuhb.jpeg?q=70",
        amount: 1,
      },
      {
        id: 11,
        title: "ASUS ROG (Black, 128 GB)  (8 GB RAM)",
        author: "Asus",
        price: 83000,
        img:"https://rukminim2.flixcart.com/image/416/416/joynde80/mobile/b/r/s/asus-rog-zs602kl-1a002in-original-imafbb7yxwncqppd.jpeg?q=70",
        amount: 1,
      },
      {
        id: 12,
        title: "ASUS ROG (Black, 128 GB)  (8 GB RAM)",
        author: "Apple",
        price: 83000,
        img:"https://rukminim2.flixcart.com/image/416/416/k6fd47k0/mobile/z/g/r/asus-rog-phone-ii-zs660kl-1a017in-original-imafkkbmyuv5vygg.jpeg?q=70",
        amount: 1,
      },

]

export default mobiles