const fashion = [
    {
        id: 1,
        title: " Regular Fit Printed Cut Away Collar Casual Shirt",
        author: "TIGERSNAKE",
        price:700,
        img:"https://rukminim2.flixcart.com/image/832/832/khs11u80-0/shirt/y/p/c/xxl-mn0071-cndcreation-original-imafxq5fuek5vpgm.jpeg?q=70",
        amount: 1,
      },
      {
        id: 2,
        title: "Women Regular Fit Printed Cut Away Collar Casual Shirt",
        author: "TIGERSNAKE",
        price:499,
        img:"https://rukminim2.flixcart.com/image/832/832/kv1a4cw0/shirt/w/a/h/m-k-202-cndcreation-original-imag8f5nzwrdxgzg.jpeg?q=70",
        amount: 1,
      },
      {
        id: 3,
        title: "Women Regular Fit Solid Spread Collar Casual Shirt",
        author: "TIGERSNAKE",
        price:399,
        img:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/9/o/4/l-4898-901-funday-fashion-original-imagmqfehesurnhw.jpeg?q=70",
        amount: 1,
      },
      {
        id: 4,
        title: "Modern Trendy Shoes Sneakers For Men  (Orange, Grey)",
        author: "BRUTON ",
        price:799,
        img:"https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/1/i/u/-original-imaggcb7ndjv7fue.jpeg?q=70",
        amount: 1,
      },
      {
        id: 5,
        title: "High Tops For Men  (Black, Grey)",
        author: "lejano  ",
        price:599,
        img:"https://rukminim2.flixcart.com/image/832/832/l47cu4w0/shoe/v/y/b/8-blgy130-zsyto-black-original-imagf5xcydsfmhwx.jpeg?q=70",
        amount: 1,
      },
      {
        id: 6,
        title: "Slip On Sneakers For Men  (Grey)",
        author: "SUKUN ",
        price:999,
        img:"https://rukminim2.flixcart.com/image/832/832/l071d3k0/shopsy-shoe/w/o/n/6-shpf22-6-sukun-grey-original-imagcfevr66vedvz.jpeg?q=70",
        amount: 1,
      },
      {
        id: 7,
        title: "Bleed Blue Day and Date Functioning Strap Adult Quartz Analog Watch - For Men LS2821",
        author: "LIMESTONE",
        price:999,
        img:"https://rukminim2.flixcart.com/image/832/832/xif0q/watch/4/c/u/-original-imagrcjhgmzuh5dz.jpeg?q=70",
        amount: 1,
      },
      {
        id: 8,
        title: "Hampton Analog Watch - For Men AX2122#JustHere",
        author: "A/X ARMANI EXCHANGE",
        price:2999,
        img:"https://rukminim2.flixcart.com/image/832/832/xif0q/watch/z/q/r/1-ax2122-armani-exchange-men-original-imagrghgqhnptpr4.jpeg?q=70",
        amount: 1,
      },
      {
        id: 9,
        title: "G-SHOCK Analog-Digital Watch - For Men G1057 (GA-900-1ADR)",
        author: "CASIO",
        price:8999,
        img:"https://rukminim2.flixcart.com/image/832/832/kk5rgy80/watch/z/v/t/g1057-ga-900-1adr-casio-original-imafzkgr5hzguxtf.jpeg?q=70",
        amount: 1,
      },
]
export default fashion