const dashboard = [
    {
        id: 1,
        title: "OPPO Reno10 5G (Silvery Grey, 256 GB) ",
        author: "Oppo",
        price: 32000,
        img: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/e/z/d/-original-imagrn6d7ggk4wjp.jpeg?q=70",
        amount: 1,
      },
      {
        id: 2,
        title: "SAMSUNG Galaxy F13 (Sunrise Copper, 64 GB)  (4 GB RAM)",
        author: "Samsung",
        price: 10999,
        img: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/x/x/s/-original-imagfhu6dcpdnqkh.jpeg?q=70",
        amount: 1,
      },
      {
        id: 3,
        title: "Infinix SMART 7 (Azure Blue, 64 GB)  (4 GB RAM)",
        author: "infinix",
        price: 7999,
        img:"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/u/c/u/-original-imagnanh2yvpc4zx.jpeg?q=70",
        amount: 1,
      },
      {
        id: 4,
        title: "My First Book of Pencil Control",
        author: "by Wonder House Books | 25 April 2018",
        price: 89,
        img: "https://m.media-amazon.com/images/I/810OOg88LoL._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
      },
      {
        id: 5,
        title: "108 Panchatantra Stories",
        author: "by Maple Press  | 1 September 2020",
        price: 98,
        img: "https://m.media-amazon.com/images/I/71rmxx8P2qL._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
      },
      {
        id: 6,
        title: "Amazing Questions & Answers Science",
        author: "by Om Books Editorial Team  | 25 November 2018",
        price: 143,
        img: "https://m.media-amazon.com/images/I/81Gbz0XnW7L._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
      },
      {
        id: 7,
        title: "ASUS Vivobook 15 Core i3 11th Gen - (8 GB/256 GB SSD/Windows 11 Home) ",
        author: "Asus",
        price: 31990,
        img:"https://rukminim2.flixcart.com/image/416/416/xif0q/computer/r/e/f/-original-imagrgprbhchwgve.jpeg?q=70",
        amount: 1,
      },
      {
        id: 8,
        title: "HP 15s (2023) Ryzen 3 Dual Core 3250U - (8 GB/512 GB SSD/Windows 11 Home)",
        author: "HP",
        price: 34990,
        img:"https://rukminim2.flixcart.com/image/416/416/xif0q/computer/5/6/i/-original-imaggshd5zgfe8ev.jpeg?q=70",
        amount: 1,
      },
      {
        id: 9,
        title: "Lenovo Intel Celeron Dual Core - (8 GB/256 GB SSD/Windows 11 Home) ",
        author: "Lenovo",
        price: 28490,
        img:"https://rukminim2.flixcart.com/image/416/416/xif0q/computer/z/b/z/-original-imagmmng8dppnn4v.jpeg?q=70",
        amount: 1,
      },
      {
        id: 10,
        title: " Regular Fit Printed Cut Away Collar Casual Shirt",
        author: "TIGERSNAKE",
        price:700,
        img:"https://rukminim2.flixcart.com/image/832/832/khs11u80-0/shirt/y/p/c/xxl-mn0071-cndcreation-original-imafxq5fuek5vpgm.jpeg?q=70",
        amount: 1,
      },
      {
        id: 11,
        title: "Women Regular Fit Printed Cut Away Collar Casual Shirt",
        author: "TIGERSNAKE",
        price:499,
        img:"https://rukminim2.flixcart.com/image/832/832/kv1a4cw0/shirt/w/a/h/m-k-202-cndcreation-original-imag8f5nzwrdxgzg.jpeg?q=70",
        amount: 1,
      },
      {
        id: 12,
        title: "Women Regular Fit Solid Spread Collar Casual Shirt",
        author: "TIGERSNAKE",
        price:399,
        img:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/9/o/4/l-4898-901-funday-fashion-original-imagmqfehesurnhw.jpeg?q=70",
        amount: 1,
      },
      {
        id: 13,
        title: "Modern Trendy Shoes Sneakers For Men  (Orange, Grey)",
        author: "BRUTON ",
        price:799,
        img:"https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/1/i/u/-original-imaggcb7ndjv7fue.jpeg?q=70",
        amount: 1,
      },
      {
        id: 14,
        title: "High Tops For Men  (Black, Grey)",
        author: "lejano  ",
        price:599,
        img:"https://rukminim2.flixcart.com/image/832/832/l47cu4w0/shoe/v/y/b/8-blgy130-zsyto-black-original-imagf5xcydsfmhwx.jpeg?q=70",
        amount: 1,
      },
      {
        id: 15,
        title: "Slip On Sneakers For Men  (Grey)",
        author: "SUKUN ",
        price:999,
        img:"https://rukminim2.flixcart.com/image/832/832/l071d3k0/shopsy-shoe/w/o/n/6-shpf22-6-sukun-grey-original-imagcfevr66vedvz.jpeg?q=70",
        amount: 1,
      },
      {
        id: 16,
        title: "Bleed Blue Day and Date Functioning Strap Adult Quartz Analog Watch - For Men LS2821",
        author: "LIMESTONE",
        price:999,
        img:"https://rukminim2.flixcart.com/image/832/832/xif0q/watch/4/c/u/-original-imagrcjhgmzuh5dz.jpeg?q=70",
        amount: 1,
      },
      {
        id: 17,
        title: "Hampton Analog Watch - For Men AX2122#JustHere",
        author: "A/X ARMANI EXCHANGE",
        price:2999,
        img:"https://rukminim2.flixcart.com/image/832/832/xif0q/watch/z/q/r/1-ax2122-armani-exchange-men-original-imagrghgqhnptpr4.jpeg?q=70",
        amount: 1,
      },
      {
        id: 18,
        title: "G-SHOCK Analog-Digital Watch - For Men G1057 (GA-900-1ADR)",
        author: "CASIO",
        price:8999,
        img:"https://rukminim2.flixcart.com/image/832/832/kk5rgy80/watch/z/v/t/g1057-ga-900-1adr-casio-original-imafzkgr5hzguxtf.jpeg?q=70",
        amount: 1,
      },
      {
        id: 19,
        title: " Top Load Washing Machine Grey  (RMFA75A5G)",
        author: "Relme",
        price:14999,
        img:"https://rukminim2.flixcart.com/image/416/416/kufuikw0/washing-machine-new/a/c/c/rmfa75a5g-realme-techlife-original-imag7k8dp5xfsmg4.jpeg?q=70",
        amount: 1,
      },
      {
        id: 20,
        title: " LG 242 L Frost Free Double Door 3 Star Refrigerator with Smart Inverter  ",
        author: "LG",
        price:44999,
        img:"https://rukminim2.flixcart.com/image/416/416/xif0q/refrigerator-new/t/x/s/-original-imaghtghjcf67haj.jpeg?q=70",
        amount: 1,
      },
      {
        id: 21,
        title: "G-SHOCK Analog-Digital Watch - For Men G1057 (GA-900-1ADR)",
        author: "CASIO",
        price:8999,
        img:"https://rukminim2.flixcart.com/image/832/832/kk5rgy80/watch/z/v/t/g1057-ga-900-1adr-casio-original-imafzkgr5hzguxtf.jpeg?q=70",
        amount: 1,
      }
    ]
    
    export default dashboard